apiVersion: v1
kind: Pod
metadata:
  name: pod
  namespace: {{ .Namespace }}
spec:
  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          name: web
      volumeMounts:
        - name: config
          mountPath: /usr/share/nginx/html
  volumes:
    - name: config
      configMap:
        name: {{ .Name }}-config
