---
# framework type

apiVersion: kudo.k8s.io/v1alpha1
kind: Framework
metadata:
  name: myservice-type
  labels:
    controller-tools.k8s.io: "1.0"

---
# framework implementation

apiVersion: kudo.k8s.io/v1alpha1
kind: FrameworkVersion
metadata:
  name: myservice-impl-v1
  namespace: default
  labels:
    controller-tools.k8s.io: "1.0"
spec:
  version: "1.0.0"
  connectionString: ""
  framework:
    name: myservice-type
    kind: Framework
  parameters:
    - name: WHO
      default: "Ravi"
  templates:
    config.yaml: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: config
        namespace: {{ .Namespace }}
      data:
        index.html: |
          {{ .Params.WHO }}, hello from {{ .Name }} !!!
    pod.yaml: |
      apiVersion: v1
      kind: Pod
      metadata:
        name: pod
        namespace: {{ .Namespace }}
      spec:
        containers:
          - name: nginx
            image: nginx
            ports:
              - containerPort: 80
                name: web
            volumeMounts:
              - name: config
                mountPath: /usr/share/nginx/html
        volumes:
          - name: config
            configMap:
              name: {{ .Name }}-config
  tasks:
    deploy-task:
      resources:
        - config.yaml
        - pod.yaml
  plans:
    deploy:
      strategy: serial
      phases:
        - name: deploy-phase
          strategy: parallel
          steps:
            - name: deploy-step
              tasks:
                - deploy-task

---
# framework instance

apiVersion: kudo.k8s.io/v1alpha1
kind: Instance
metadata:
  name: myservice
  labels:
    controller-tools.k8s.io: "1.0"
    framework: myservice-type
spec:
  frameworkVersion:
    name: myservice-impl-v1
    namespace: default
    type: FrameworkVersions
  parameters:
    WHO: "Matt"
